query brightness correctly

diff --git a/driver/Makefile.in b/driver/Makefile.in
--- a/driver/Makefile.in
+++ b/driver/Makefile.in
@@ -64,14 +64,14 @@ WAYLAND_DPY_OBJS_1 = wayland-dpy.o
 WAYLAND_IDLE_OBJS   = @WAYLAND_IDLE_OBJS@
 WAYLAND_IDLE_SRCS   = wayland-idle.c
 WAYLAND_IDLE_OBJS_1 = wayland-idle.o \
-		      $(WAYLAND_PROTO)/ext-idle-notify-v1-protocol.o \
-		      $(WAYLAND_PROTO)/idle-protocol.o
+			  $(WAYLAND_PROTO)/ext-idle-notify-v1-protocol.o \
+			  $(WAYLAND_PROTO)/idle-protocol.o
 
 WAYLAND_DPMS_OBJS   = @WAYLAND_DPMS_OBJS@
 WAYLAND_DPMS_SRCS   = wayland-dpms.c
 WAYLAND_DPMS_OBJS_1 = wayland-dpms.o \
-		      $(WAYLAND_PROTO)/wlr-output-power-management-unstable-v1-protocol.o \
-		      $(WAYLAND_PROTO)/dpms-protocol.o
+			  $(WAYLAND_PROTO)/wlr-output-power-management-unstable-v1-protocol.o \
+			  $(WAYLAND_PROTO)/dpms-protocol.o
 
 WAYLAND_LOCK_OBJS   = @WAYLAND_LOCK_OBJS@
 WAYLAND_LOCK_SRCS   = wayland-lock.c
@@ -81,7 +81,7 @@ WAYLAND_LOCK_OBJS_1 = wayland-lock.o \
 WAYLAND_GTK_OBJS    = @WAYLAND_GTK_OBJS@
 WAYLAND_GTK_SRCS    = wayland-dpms.c
 WAYLAND_GTK_OBJS_1  = $(WAYLAND_DPY_OBJS) $(WAYLAND_IDLE_OBJS) \
-		      $(WAYLAND_DPMS_OBJS)
+			  $(WAYLAND_DPMS_OBJS)
 
 HACKDIR		= @HACKDIR@
 HACK_CONF_DIR	= @HACK_CONF_DIR@
@@ -219,12 +219,12 @@ AUTH_LIBS	= $(LIBS_PRE) $(XFT_LIBS) $(XINPUT_LIBS) $(XINERAMA_LIBS) \
 		  $(XDPMS_LIBS) @SAVER_LIBS@ -lXt -lX11 -lXext -lXi \
 		  @PASSWD_LIBS@ $(LIBS_POST) $(INTL_LIBS)
 
-SYSTEMD_DEFS	= 
+SYSTEMD_DEFS	=
 SYSTEMD_SRCS	= xscreensaver-systemd.c
 SYSTEMD_OBJS	= xscreensaver-systemd.o blurb.o $(UTILS_BIN)/yarandom.o
 SYSTEMD_LIBS	= $(LIBS_PRE) @SYSTEMD_LIBS@ -lX11 $(LIBS_POST)
 
-CMD_DEFS	= 
+CMD_DEFS	=
 CMD_SRCS	= remote.c xscreensaver-command.c
 CMD_OBJS	= remote.o xscreensaver-command.o blurb.o atoms.o clientmsg.o
 CMD_LIBS	= $(LIBS_PRE) $(XINPUT_LIBS) -lX11 -lXext $(LIBS_POST)
@@ -355,19 +355,19 @@ install-program:: $(SETUID_EXES)
 	 for exe in $(SETUID_EXES); do					      \
 	   echo $$inst $$exe $$idir/$$exe ;				      \
 	   if   $$inst $$exe $$idir/$$exe ; then			      \
-	     true ;							      \
+		 true ;							      \
 	   elif [ @SETUID_AUTH@ = yes ]; then				      \
-	     echo $(INSTALL_PROGRAM) $$exe $$idir/$$exe ;		      \
-	     if   $(INSTALL_PROGRAM) $$exe $$idir/$$exe ; then		      \
-	       echo "" ;						      \
-	       echo "WARNING: unable to install $$exe setuid." ;	      \
-	       echo "WARNING: authentication may not work!" ;		      \
-	       echo "" ;						      \
-	     else							      \
-	       exit 1 ;							      \
-	     fi ;							      \
+		 echo $(INSTALL_PROGRAM) $$exe $$idir/$$exe ;		      \
+		 if   $(INSTALL_PROGRAM) $$exe $$idir/$$exe ; then		      \
+		   echo "" ;						      \
+		   echo "WARNING: unable to install $$exe setuid." ;	      \
+		   echo "WARNING: authentication may not work!" ;		      \
+		   echo "" ;						      \
+		 else							      \
+		   exit 1 ;							      \
+		 fi ;							      \
 	   else								      \
-	     exit 1 ;							      \
+		 exit 1 ;							      \
 	   fi ;								      \
 	 done
 
@@ -376,7 +376,7 @@ install-program:: $(SETUID_EXES)
 install-program::
 	@D=$(DESTDIR)$(bindir) ;					      \
 	 echo ln -sf xscreensaver-settings $$D/xscreensaver-demo ; 	      \
-	      ln -sf xscreensaver-settings $$D/xscreensaver-demo
+		  ln -sf xscreensaver-settings $$D/xscreensaver-demo
 
 install-ad: XScreenSaver.ad
 	@if [ ! -d $(DESTDIR)$(AD_DIR) ]; then				      \
@@ -398,7 +398,7 @@ install-ad: XScreenSaver.ad
  $$e "           to malfunction.  Please delete it!"			     ;\
  $$e "  ####################################################################";\
  $$e ""									     ;\
-	    exit 1 ;							      \
+		exit 1 ;							      \
 	  else								      \
  $$e ""									     ;\
  $$e "  ####################################################################";\
@@ -406,7 +406,7 @@ install-ad: XScreenSaver.ad
  $$e "           This is probably ok; it should work without that file."     ;\
  $$e "  ####################################################################";\
  $$e ""									     ;\
-	    exit 0 ;							      \
+		exit 0 ;							      \
 	  fi								      \
 	fi
 
@@ -421,7 +421,7 @@ install-man:: $(MENA) $(MENB)
 	@								\
 	U=$(UTILS_SRC)/version.h ;					\
 	V=`sed -n 's/.*xscreensaver \([0-9]\.[^)]*)\).*/\1/p' < $$U |	\
-	    head -1` ;							\
+		head -1` ;							\
 	T=/tmp/xs$$$$.man ;						\
 	SUFA=$(mansuffixA) ;						\
 	SUFB=$(mansuffixB) ;						\
@@ -430,17 +430,17 @@ install-man:: $(MENA) $(MENB)
 	  TH=".TH XScreenSaver $$SUF \"$$V\" \"X Version 11\"" ;	\
 	  DIR="$(DESTDIR)$(mandir)/man$$SUF" ;				\
 	  if [ ! -d $$DIR ]; then					\
-	    echo $(INSTALL_DIRS) $$DIR ;				\
-	         $(INSTALL_DIRS) $$DIR ;				\
+		echo $(INSTALL_DIRS) $$DIR ;				\
+			 $(INSTALL_DIRS) $$DIR ;				\
 	   fi ;								\
 									\
 	  sed -e "s/^\.TH.*/$$TH/"					\
-	      -e "s/^\(\.BR xscreens[^ ]* (\)[0-9]\(.*\)/\1$$SUFA\2/"	\
-	      -e "s@(MANSUFFIX)@($$SUFB)@g"				\
-	    < $(srcdir)/$$man > $$T ;					\
+		  -e "s/^\(\.BR xscreens[^ ]* (\)[0-9]\(.*\)/\1$$SUFA\2/"	\
+		  -e "s@(MANSUFFIX)@($$SUFB)@g"				\
+		< $(srcdir)/$$man > $$T ;					\
 	  manbase=`echo $$man | sed 's/\.man$$//'` ;			\
 	  echo $(INSTALL_DATA) $$man $$DIR/$$manbase.$$SUF ;		\
-	       $(INSTALL_DATA) $$T   $$DIR/$$manbase.$$SUF ;		\
+		   $(INSTALL_DATA) $$T   $$DIR/$$manbase.$$SUF ;		\
 	} ;								\
 									\
 	SUF=$$SUFA ; for man in $(MENA); do INST ; done ;		\
@@ -453,7 +453,7 @@ install-man::
 	 F1=xscreensaver-settings.$(mansuffixA) ;			\
 	 F2=xscreensaver-demo.$(mansuffixA) ;				\
 	 echo ln -sf $$F1 $$D/$$F2 ;					\
-	      ln -sf $$F1 $$D/$$F2
+		  ln -sf $$F1 $$D/$$F2
 
 # These used to be in driver/ and installed into /usr/bin/
 # Now they are in hacks/ and are installed into /usr/libexec/xscreensaver/
@@ -512,22 +512,22 @@ install-pam: xscreensaver.pam
 	  fi ;								\
 									\
 	  if [ -z "$$src2" ]; then					\
-	    echo $(INSTALL_DATA) $$src $$dir/$$name ;			\
-	         $(INSTALL_DATA) $$src $$dir/$$name ;			\
+		echo $(INSTALL_DATA) $$src $$dir/$$name ;			\
+			 $(INSTALL_DATA) $$src $$dir/$$name ;			\
 	  else								\
-	    tmp="xscreensaver.pam.$$$$" ;				\
-	    grep '^#%\|^auth\|^@include' $$src2 > $$tmp ;		\
-	    if cmp -s $$tmp $$dir/$$name ; then				\
-	      echo "$$dir/$$name unchanged" ;				\
-	    else							\
-	      echo "Updating contents of $$dir/$$name from $$src2" ;	\
-	      $(INSTALL_DATA) $$tmp $$dir/$$name ;			\
-	    fi ;							\
-	    rm -f $$tmp ;						\
+		tmp="xscreensaver.pam.$$$$" ;				\
+		grep '^#%\|^auth\|^@include' $$src2 > $$tmp ;		\
+		if cmp -s $$tmp $$dir/$$name ; then				\
+		  echo "$$dir/$$name unchanged" ;				\
+		else							\
+		  echo "Updating contents of $$dir/$$name from $$src2" ;	\
+		  $(INSTALL_DATA) $$tmp $$dir/$$name ;			\
+		fi ;							\
+		rm -f $$tmp ;						\
 	  fi ;								\
 									\
 	  if [ ! -f $$dir/$$name ]; then				\
-	    e=echo ;							\
+		e=echo ;							\
  $$e ""									     ;\
  $$e "  ####################################################################";\
  $$e "  Warning: xscreensaver has been compiled with support for Pluggable"  ;\
@@ -541,24 +541,24 @@ install-pam: xscreensaver.pam
 	  if ( grep $$name $$conf >/dev/null ); then			\
 	   echo "$$conf unchanged: already has an entry for $$name" ;   \
 	  else								\
-	    tmp="pam.conf.$$$$" ;					\
-	    grep -v $$name $$conf > $$tmp ;				\
-	    extras=`sed -n "s/^login\(.*auth.*\)$$/$$name\1/p" $$conf`; \
-	    echo "$$extras" >> $$tmp ;					\
-	    if [ "x$$extras" = "x" ]; then				\
-	      echo "Error: no login rules in $$conf?" >&2 ;		\
-	    else							\
-	      echo "adding $$name rules to $$conf:" ;			\
-	      echo "" ;							\
-	      echo "$$extras" | sed 's/^/	/' ;			\
-	    fi ; 							\
-	    $(INSTALL_DATA) $$tmp $$conf ;				\
-	    rm -f $$tmp ;						\
+		tmp="pam.conf.$$$$" ;					\
+		grep -v $$name $$conf > $$tmp ;				\
+		extras=`sed -n "s/^login\(.*auth.*\)$$/$$name\1/p" $$conf`; \
+		echo "$$extras" >> $$tmp ;					\
+		if [ "x$$extras" = "x" ]; then				\
+		  echo "Error: no login rules in $$conf?" >&2 ;		\
+		else							\
+		  echo "adding $$name rules to $$conf:" ;			\
+		  echo "" ;							\
+		  echo "$$extras" | sed 's/^/	/' ;			\
+		fi ; 							\
+		$(INSTALL_DATA) $$tmp $$conf ;				\
+		rm -f $$tmp ;						\
 	  fi ;								\
 	  if ( grep $$name $$conf >/dev/null ); then			\
-	    echo ;							\
+		echo ;							\
 	  else								\
-	    e=echo ;							\
+		e=echo ;							\
  $$e ""									     ;\
  $$e "  ####################################################################";\
  $$e "  Warning: xscreensaver has been compiled with support for Pluggable"  ;\
@@ -569,7 +569,7 @@ install-pam: xscreensaver.pam
  $$e ""									     ;\
 	  fi ;								\
 	else								\
-	    e=echo ;							\
+		e=echo ;							\
  $$e ""									     ;\
  $$e "  ####################################################################";\
  $$e "  Warning: $$dir/ does not exist, not installing PAM config."          ;\
@@ -640,9 +640,9 @@ update-icon-caches::
 		  /usr/share/pixmaps/*/index.theme			      \
 	 ; do								      \
 	   if [ -f $$f ]; then						      \
-	     f=`dirname $$f`						     ;\
-	     echo $(UPDATE_ICON_CACHE) --force --quiet $$f		     ;\
-	          $(UPDATE_ICON_CACHE) --force --quiet $$f		     ;\
+		 f=`dirname $$f`						     ;\
+		 echo $(UPDATE_ICON_CACHE) --force --quiet $$f		     ;\
+			  $(UPDATE_ICON_CACHE) --force --quiet $$f		     ;\
 	   fi								     ;\
 	 done
 
@@ -690,7 +690,7 @@ uninstall-old-gnome-icons::
 	   "$(DESTDIR)$(GTK_ICONDIR)/xscreensaver.svg"			     ;\
 	 do								      \
 	   if [ -f "$$f" ]; then					      \
-	     echo rm -f "$$f"						     ;\
+		 echo rm -f "$$f"						     ;\
 		  rm -f "$$f"						     ;\
 	   fi								     ;\
 	 done
@@ -708,7 +708,7 @@ install-xml:
 	 fi ;								\
 	 src=$(srcdir)/../hacks/config ;				\
 	 echo $(INSTALL_DATA) $$src/README $$dest/README ;		\
-	      $(INSTALL_DATA) $$src/README $$dest/README
+		  $(INSTALL_DATA) $$src/README $$dest/README
 
 
 # /usr/share/xscreensaver/config/README
@@ -760,17 +760,17 @@ distdepend: check_men update_ad_version XScreenSaver_ad.h XScreenSaver_Xm_ad.h
 	(								    \
 	  awk '/^# .*Makefile.in ---/,/^# DO .*distdepend/' < Makefile.in ; \
 	  sed -e '/^#.*/d'						    \
-	      -e 's@ \./@ @g;s@ /[^ ]*@@g;/^.*:$$/d'			    \
-	      -e 's@\.\./utils@$$(UTILS_SRC)@g'				    \
-	      -e 's@ \([^$$]\)@ $$(srcdir)/\1@g'			    \
-	      -e 's@$$.*\(XScreenSaver_ad\)@\1@g'			    \
-	      -e 's@$$.*\(XScreenSaver_Xm_ad\)@\1@g'			    \
-	      -e 's@ $$(srcdir)/\(.*config\.h\)@ \1@g' ;		    \
+		  -e 's@ \./@ @g;s@ /[^ ]*@@g;/^.*:$$/d'			    \
+		  -e 's@\.\./utils@$$(UTILS_SRC)@g'				    \
+		  -e 's@ \([^$$]\)@ $$(srcdir)/\1@g'			    \
+		  -e 's@$$.*\(XScreenSaver_ad\)@\1@g'			    \
+		  -e 's@$$.*\(XScreenSaver_Xm_ad\)@\1@g'			    \
+		  -e 's@ $$(srcdir)/\(.*config\.h\)@ \1@g' ;		    \
 	  echo ''							    \
 	) > /tmp/distdepend.$$$$ &&					    \
 	mv /tmp/distdepend.$$$$ Makefile.in
 
-# Updates the version number in the app-defaults file to be in sync with 
+# Updates the version number in the app-defaults file to be in sync with
 # the version number in version.h.  This is so people can tell when they
 # have a version skew between the app-defaults file and the executable.
 # Also update hacks/config/README in the same way.
@@ -782,17 +782,17 @@ update_ad_version::
   Y=`date '+%Y'` ;							    \
   D=`date '+%d-%b-%Y'` ;						    \
   for S in $$files ; do							    \
-    T=/tmp/xs.$$$$ ;							    \
-    sed -e "s/\(.*version \)[0-9][0-9]*\.[0-9.]*[ab]*[0-9]*\(.*\)/\1$$V\2/" \
-        -e "s/\([0-9][0-9]-[A-Z][a-z][a-z]-[0-9][0-9][0-9]*\)/$$D/"	    \
-        -e "s/\( [0-9][0-9][0-9][0-9]-\)[0-9][0-9][0-9][0-9] /\1$$Y /"	    \
-      < $$S > $$T ;							    \
-    if cmp -s $$S $$T ; then						    \
-      true ;								    \
-    else								    \
-      cat $$T > $$S ;							    \
-      echo "updated $$S to $$V $$D" ;					    \
-    fi ;								    \
+	T=/tmp/xs.$$$$ ;							    \
+	sed -e "s/\(.*version \)[0-9][0-9]*\.[0-9.]*[ab]*[0-9]*\(.*\)/\1$$V\2/" \
+		-e "s/\([0-9][0-9]-[A-Z][a-z][a-z]-[0-9][0-9][0-9]*\)/$$D/"	    \
+		-e "s/\( [0-9][0-9][0-9][0-9]-\)[0-9][0-9][0-9][0-9] /\1$$Y /"	    \
+	  < $$S > $$T ;							    \
+	if cmp -s $$S $$T ; then						    \
+	  true ;								    \
+	else								    \
+	  cat $$T > $$S ;							    \
+	  echo "updated $$S to $$V $$D" ;					    \
+	fi ;								    \
   done ;								    \
   rm $$T
 
@@ -808,7 +808,7 @@ check_men:
 	@badmen="" ;							\
 	 for exe in $(EXES); do						\
 	   if ! [ -f $(srcdir)/$$exe.man ]; then			\
-	     badmen="$$badmen $$exe" ;					\
+		 badmen="$$badmen $$exe" ;					\
 	   fi ;								\
 	 done ;								\
 	 if [ -n "$$badmen" ]; then					\
@@ -816,7 +816,7 @@ check_men:
 	   echo "Warning: The following programs have no manuals:" ;	\
 	   echo "" ;							\
 	   for m in $$badmen ; do					\
-	     echo "    $$m" ;						\
+		 echo "    $$m" ;						\
 	   done ;							\
 	   echo "" ;							\
 	 fi
@@ -913,7 +913,7 @@ xscreensaver-gfx.o: XScreenSaver_ad.h
 xscreensaver-gfx.o: xscreensaver-gfx.c
 	$(CC) -c $(CC_ALL) $(GFX_DEFS) $<
 xscreensaver-gfx: $(GFX_OBJS)
-	$(CC) $(LDFLAGS) -o $@ $(GFX_OBJS) $(GFX_LIBS)
+	$(CC) $(LDFLAGS) -o $@ $(GFX_OBJS) $(GFX_LIBS) -lm
 
 dialog.o: dialog.c
 	$(CC) -c $(CC_ALL) $(AUTH_DEFS) $<
@@ -963,12 +963,12 @@ xscreensaver-settings-Xm: $(MOTIF_OBJS)
 xscreensaver-settings: @PREFERRED_DEMO_PROGRAM@
 	@if [ "@PREFERRED_DEMO_PROGRAM@" = "" ]; then			\
 	  echo "WARNING: neither GTK nor Motif are available,"		\
-	       "therefore no xscreensaver-settings!"		      ; \
+		   "therefore no xscreensaver-settings!"		      ; \
 	  rm -f $@@EXEEXT@					      ;	\
 	else								\
 	       rm -f $@@EXEEXT@					      ;	\
 	  echo cp -p @PREFERRED_DEMO_PROGRAM@@EXEEXT@ $@@EXEEXT@      ;	\
-	       cp -p @PREFERRED_DEMO_PROGRAM@@EXEEXT@ $@@EXEEXT@      ;	\
+		   cp -p @PREFERRED_DEMO_PROGRAM@@EXEEXT@ $@@EXEEXT@      ;	\
 	fi
 
 
